"use client";

import { DownloadIcon } from "lucide-react";

import { Button } from "@/components/ui/button";

interface DownloadSummaryButtonProps {
  title: string;
  summaryText: string;
  fileName: string;
  createdAt: string;
}

export const DownloadSummaryButton = ({
  title,
  summaryText,
  fileName,
  createdAt,
}: DownloadSummaryButtonProps) => {
  const handleDownload = () => {
    const summaryContent = `# ${title}
Generated Summary
Generated on ${new Date(createdAt).toLocaleDateString()}

${summaryText}
    
Original File: ${fileName}
Generated by Sommaire
    `;

    const blob = new Blob([summaryContent], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `Sommaire-${title.replace(/[^a-zA-Z0-9]/gi, "_")}.txt`;
    document.body.appendChild(a);
    a.click();

    // Remove the anchor element from the DOM
    document.body.removeChild(a);

    // Clean up the URL object
    URL.revokeObjectURL(url);
  };

  return (
    <Button
      size="sm"
      className="h-8 bg-rose-100 px-3 text-rose-600 hover:bg-rose-50 hover:text-rose-700"
      onClick={handleDownload}
    >
      <DownloadIcon className="mr-2 size-4" />
      Download Summary
    </Button>
  );
};
